name: CMake Build
on:
    push:
        branches: ["main", "dev"]
        paths-ignore:
          - 'README.md'
          - 'docs/**'
permissions: write-all
jobs:
    build:
        name: Build Visual Studio 2022
        runs-on: windows-2022
        steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive
        - uses: TheMrMilchmann/setup-msvc-dev@v2
          with:
            arch: x86
            toolset: 14.39
            export-path-to-vcvarsall: VCVARSALL
        - name: CMake Setup
          uses: lukka/get-cmake@latest
        - name: CMake Configure
          run: 'cmake --preset x86-release'
        - name: Ninja Build
          run: ninja -C out/build/x86-release -j 20
        - name: CMake Install
          run: cmake --install out/build/x86-release --prefix out/install/x86-release
        - name: Archive DLL
          uses: actions/upload-artifact@v4
          with:
            name: dll-release
            path: out/install/x86-release/bin/*.dll
        - name: Archive VDF
          uses: actions/upload-artifact@v4
          with:
            name: vdf-release
            path: out/install/x86-release/*.vdf